"""created db migratory class

Revision ID: b74e977998e2
Revises: 
Create Date: 2022-05-09 11:09:11.399750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74e977998e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('secondname', sa.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('teachers', sa.VARCHAR(length=25), nullable=False),
    sa.Column('students', sa.VARCHAR(length=400), nullable=False),
    sa.Column('support', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
